import type {PreviewBundle} from './preview';
import previewRuntime from '../../local-runtime/preview.mjs?raw';
import integrityRuntime from '../../local-runtime/integrity.mjs?raw';
import engine from '../../local-runtime/engine.mjs?raw';
import dev from '../../local-runtime/dev.mjs?raw';
import pack from '../../local-runtime/pack.mjs?raw';
import platform from '../../local-runtime/platform.mjs?raw';
import browserPlatform from '../../local-runtime/platform-browser.mjs?raw';
import twig from '../../local-runtime/twig.mjs?raw';
import pkg from '../../local-runtime/package.json?raw';
import lock from '../../local-runtime/package-lock.json?raw';
const json = (value: unknown) => JSON.stringify(value, null, 2) + '\n';
export function localKit(paths: string[], storeName = 'Loja local', preview?: PreviewBundle): Record<string, string> {
  const normalized = storeName.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80) || 'loja-local';
  const slug = /^(con|prn|aux|nul|com[0-9]|lpt[0-9])$/i.test(normalized) ? 'loja-' + normalized : normalized;
  const projectPackage = JSON.parse(pkg), projectLock = JSON.parse(lock);
  projectPackage.name = slug; projectLock.name = slug; projectLock.packages[''].name = slug;
  const templates = paths.filter(p => p.startsWith('templates/') && p.endsWith('.twig'));
  const sectionFiles = paths.filter(p => p.startsWith('sections/') && p.endsWith('.twig'));
  const sections = Object.fromEntries(sectionFiles.map(p => [p.slice(9, -5), p]));
  for (const p of sectionFiles) {
    const alias = p.split('/').at(-1)!.slice(0, -5);
    if (sectionFiles.filter(f => f.split('/').at(-1) === p.split('/').at(-1)).length === 1) sections[alias] = p;
  }
  const image = '/__local/placeholder.svg';
  const prices = {price: 100, price_formated: 'R$ 100,00', sale_price: 100, sale_price_formated: 'R$ 100,00', has_promotion: false, discount: 0, installments: [], billet_discount: 0};
  const product = {id: 1, name: 'Produto fictício', sku: 'LOCAL-001', url_path: '/preview?page=product', active: true, availability: 'Disponível', warranty: 'Exemplo local', brand: {data: {name: 'Marca fictícia'}}, prices: {data: prices}, texts: {data: {description: 'Produto fictício para conferir o layout.'}}, images: {data: [{id: 1, url: image, src: image, src_zoom: image, src_thumb: image, width: 640, height: 640}]}, skus: {data: []}, flags: {data: []}, breadcrumbs: {data: []}, extras: {data: {}}, variations: {data: []}, reviews: {data: []}, customizations: {data: []}, specifications: {data: []}};
  const category = {id: 1, name: 'Categoria fictícia', url_path: '/preview?page=category', children: {data: []}, image_url: image};
  const params = {fonts_texts_family: 'Arial', fonts_titles_family: 'Arial', highlight_type_payment: 'promotional', color_general_background: '#ffffff', custom_css: '', show_dark_mode: false, cart_type: 'side_cart'};
  const section = (alias: string, order: number) => ({section_alias: alias, visible: true, order, params: {title: 'Prévia local fictícia', products_per_page: 12, filters_enabled: false, show_sku: true, show_availability: true, show_warranty: false, layout: 'container', slider_delay: 5, resource: {ids: [1], dimensions: {width: 1200, height: 400}, first_banner: {id: 1, image_url: image}}, collection_id: 1, collection: {id: 1}, show_title: true, mobile_products_per_line: 2, visible_products: 12, desktop_layout: 'grid', show_all_button: true, header_layout: 'inline', menu_text_color: '#222222', text_color: '#222222', background_color: '#ffffff', cart_icon_color: '#222222', searchbar_enabled: true, categories_enabled: true, categories_type: 'all', show_brand: true, show_description: true}});
  const pageSections = Object.fromEntries(Object.entries({home: ['main_banner', 'collection'], category: ['category_content'], product: ['product_content'], promotion: ['promotion_content'], pages: ['base_page_content']}).map(([page, aliases]) => [page, aliases.filter(alias => sections[alias]).map(section)]));
  const globalStyles = ['assets/styles/global/main.scss', 'assets/styles/global/main.css'].filter(p => paths.includes(p));
  const styles = globalStyles.length ? globalStyles : paths.filter(p => /^assets\/styles\/global\/[^/]+\.(s?css)$/.test(p) && !p.split('/').at(-1)!.startsWith('_'));
  const mobileStyles = paths.filter(p => /^assets\/styles\/global\/main-mobile\.(s?css)$/.test(p));
  const pageStyles = Object.fromEntries(templates.map(p => {const page = p.slice(10, -5); return [page, paths.filter(file => file === `assets/styles/pages/${page}.scss`)];}));
  const mobilePageStyles = Object.fromEntries(templates.map(p => {const page = p.slice(10, -5); return [page, paths.filter(file => file === `assets/styles/pages/mobile/${page}.scss`)];}));
  return {
    'package.json': json(projectPackage), 'package-lock.json': json(projectLock),
    '.yampi-sync/tools/engine.mjs': engine, '.yampi-sync/tools/dev.mjs': dev, '.yampi-sync/tools/pack.mjs': pack,
    '.yampi-sync/tools/platform.mjs': platform, '.yampi-sync/tools/platform-browser.mjs': browserPlatform, '.yampi-sync/tools/twig.mjs': twig, '.yampi-sync/tools/preview.mjs':previewRuntime, '.yampi-sync/tools/integrity.mjs':integrityRuntime,
    'local.config.json': json({port: 5182, pages: Object.fromEntries(templates.map(p => [p.slice(10, -5), p])), styles, mobileStyles, pageStyles, mobilePageStyles, sections}),
    'local.data.json': json({environment: 'local', isPreview: true, page: 'home', cashbacks: [], merchantData: {id: 1, alias: 'local', manifest: {name: storeName, description: 'Prévia com dados fictícios'}, domain: 'http://127.0.0.1:5182', logo_url: '', store_search_v1: true, checkout: {skip_cart: false, redirect_to: ''}, meta_tags: [], cashbacks: [], company: {name: 'Empresa fictícia', person_type: 'person', social: {}, phone: {}, whatsapp: {}, address: {}}, payments: [], pages: [], cookies_policy: {active: false}}, pageConfig: {page: 'home', theme: {alias: 'local', params}, data: {theme: {alias: 'local', params}}}, mainSectionsByPage: pageSections, mainSections: [], section: section('local', 0), sections: {header: section('header', 0), footer: section('footer', 0)}, categories: [category], sorted_categories: [category], featured_categories: [category], products: [product], product: {data: product}, banners: [{id: 1, image_url: image, image_mobile_url: image, link: '/preview?page=category', url: '/preview?page=category'}], content: {data: {data: [product], meta: {name: 'Categoria fictícia', parent: {}, total: 1}, content: 'Conteúdo fictício para a prévia local.'}, meta: {}, limit: 12}, pages: {pages: {content: {data: {name: 'Página fictícia', slug: 'pagina-local', content: {data: {content: '<p>Conteúdo fictício para conferir o layout.</p>'}}}}}}}),
    '.gitignore': 'node_modules/\n.cache/\npreview/\n*.zip\n*.env\n.env*\ntema/\n.yampi-sync/baseline/\n.yampi-sync/updates/\n.yampi-sync/manifest.json\nlocal.data.json\n',
    '.gitattributes': '* text eol=lf\ntema/** -text\n.yampi-sync/baseline/** -text\n',
    '.vscode/settings.json': json({'files.exclude': {'.yampi-sync': true, node_modules: true, '.cache': true}, 'search.exclude': {'.yampi-sync': true, node_modules: true, '.cache': true}}),
    [`${slug}.code-workspace`]: json({folders: [{path: '.', name: storeName}], settings: {}}),
    ...(preview?.source.kind !== 'demonstration' && preview?.data ? {'local.data.json':json(preview.data)} : {}),
    'README.md': `# ${storeName.replace(/[\r\n]/g, ' ')} — projeto local\n\nAbra esta pasta no VS Code, ou dê dois cliques em \`${slug}.code-workspace\`. O código da loja está em **tema/**. Os dados e recursos visuais ficam em **preview/** e não são enviados à Yampi.\n\n## Iniciar\n\nCom Node.js 24 instalado, abra o terminal nesta pasta:\n\n\`\`\`sh\nnpm ci\nnpm run dev\n\`\`\`\n\nAbra http://127.0.0.1:5182, escolha uma página e edite \`tema/\`. Recarregue para conferir. Use \`npm run check:integrity\` para conferir código/contexto e \`npm run check\` para compilar todas as páginas.\n\n## Devolver as alterações\n\nExecute \`npm run pack\` e importe o ZIP indicado no terminal em **Enviar alterações** na extensão. Também pode selecionar esta pasta inteira. Confira a comparação e confirme o envio. A publicação continua manual na Yampi.\n\n## O que há nesta pasta\n\n- **tema/**: arquivos editáveis copiados do editor da loja.\n- **local.config.json**: páginas, entradas Sass e aliases de seções.\n- **local.data.json**: contexto editável da prévia (capturado ou demonstrativo, conforme preview/report.json).\n- **.yampi-sync/**: arquivos da nossa extensão, recolhidos no VS Code. Guarda originais, manifesto com hashes e ferramentas locais. Preserve essa pasta: ela permite comparar as alterações e preparar o retorno com segurança.\n- **package.json / package-lock.json**: dependências e comandos locais.\n\nDados da prévia, imagens auxiliares, ferramentas, relatórios e configurações do VS Code não são enviados à loja.\n\n## Limites da prévia\n\nO relatório em preview/report.json informa a origem e as limitações. Configuração publicada pode diferir do rascunho; compilação não certifica fidelidade visual.\n\nA prévia compila Twig, Vue 2 e Sass e simula um conjunto explícito de helpers, mixins e leituras com contexto capturado ou demonstrativo. Configurações publicadas podem diferir do rascunho. Produtos e categorias são uma amostra datada; não há backend, estoque/preços em tempo real, pagamentos ou checkout. Chamadas externas e formulários são bloqueados. Imagens externas não capturadas geram aviso e placeholder local. Recursos capturados estão em \`preview/assets/\` e são conferidos por hash. A amostra visual não é uma exportação completa do catálogo. Se um módulo não for suportado, a prévia informa o erro. Confira também o resultado na Yampi antes de publicar. Vue 2 é mantido para compatibilidade e está fora de manutenção.\n\nImagens exportadas ficam em \`tema/assets/\`. Imagens editadas e arquivos novos não são enviados nesta versão. Não altere \`.yampi-sync/manifest.json\` ou \`.yampi-sync/baseline/\`.\n\nO projeto pode conter conteúdo privado da loja. Guarde-o fora do repositório público da extensão. O ZIP de retorno inclui somente o código editado e sua origem.\n`
  };
}
